// This file is auto-generated by scripts/openapi-react-query.ts
// Do not edit this file directly.

import { apiClient } from '@/module/core'
import type { operations } from '@/shared/types/api'
import type { FetchOptions } from "openapi-fetch"
import { OpenapiQueryClient } from "openapi-react-query"

export const useProductsUpdateVariant = (options?: Parameters<OpenapiQueryClient<'put', '/products/variants/{variantId}'>['useMutation']>['2']) => {
      // @ts-ignore
    return apiClient.useMutation('put', '/products/variants/{variantId}' as const, options)
  }
