// This file is auto-generated by scripts/openapi-react-query.ts
// Do not edit this file directly.

import { apiClient } from '@/module/core'
import type { operations } from '@/shared/types/api'
import type { FetchOptions } from "openapi-fetch"
import { OpenapiQueryClient } from "openapi-react-query"

export const useProductsFindAll = (fetchOptions?: FetchOptions<operations['ProductsController_findAll']>) => {
    return apiClient.useQuery('get', '/products' as const, fetchOptions)
  }
