// This file is auto-generated by scripts/openapi-react-query.ts
// Do not edit this file directly.

import { apiClient } from '@/module/core'
import type { operations } from '@/shared/types/api'
import type { FetchOptions } from "openapi-fetch"
import { OpenapiQueryClient } from "openapi-react-query"

export const useUserGetProfile = (fetchOptions?: FetchOptions<operations['UserController_getProfile']>) => {
    return apiClient.useQuery('get', '/user/profile' as const, fetchOptions)
  }
