// This file is auto-generated by scripts/openapi-react-query.ts
// Do not edit this file directly.

import { apiClient } from '@/module/core'
import type { operations } from '@/shared/types/api'
import type { FetchOptions } from "openapi-fetch"
import { OpenapiQueryClient } from "openapi-react-query"

export const useCartAddToCart = (options?: Parameters<OpenapiQueryClient<'post', '/cart/items'>['useMutation']>['2']) => {
      // @ts-ignore
    return apiClient.useMutation('post', '/cart/items' as const, options)
  }
