// This file is auto-generated by scripts/openapi-react-query.ts
// Do not edit this file directly.

import { apiClient } from '@/module/core'
import type { operations } from '@/shared/types/api'
import type { FetchOptions } from "openapi-fetch"
import { OpenapiQueryClient } from "openapi-react-query"

export const useOrderFindOne = (
        fetchOptions?: FetchOptions<operations['OrderController_findOne']>,
        options?: Parameters<OpenapiQueryClient<'get', '/order/{id}'>['useQuery']>['3']
      ) => {
    // @ts-ignore
    return apiClient.useQuery('get', '/order/{id}' as const, fetchOptions, options)
  }
